add design critique tips
ddd-crew/bounded-context-canvas pull request #13
Opened 2020-08-24 07:57 UTC by NTCoding

2020-08-25 08:46 UTC, yellowbrickc requested changes
Regarding https://raw.githubusercontent.com/ddd-crew/bounded-context-canvas/5e2d22e316c36b61d4927f11f1aa08b3bdd31555/resources/bounded-context-canvas-design-critique-tips.jpg
1. are the names of **the** messages coherent ...
2. **are** the types of each message correct? What you change it? <- what do you mean?

2020-08-26 15:05 UTC, NTCoding commented
@yellowbrickc Thanks for catching those typos. I need to get my eyes tested.

2020-08-26 15:35 UTC, NTCoding commented
I decided to replace the image with text so that it's possible for other people to contribute.

2020-08-26 16:14 UTC, yellowbrickc approved these changes

2020-08-26 16:17 UTC, merged